# Designed for ZSH on Fedora with Gnome

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3600000

palette = "mocha"
right_format = """$all"""
format = """
$os\
$username\
$directory\
$character\
"""
add_newline = false

[line_break]
disabled = false

[username]
show_always = true
style_user = "fg:text"
style_root = "bold red"
format = "[$user]($style)"
disabled = true

[os]
style = "fg:blue"
disabled = true # Disabled by default
symbols.Fedora = " "

[directory]
style = "fg:blue"
format = "[ $path]($style)"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "subtext0" 
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold red"
#format = '[$all_status$ahead_behind ]($style)'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[git_metrics]
format = "([+$added]($added_style)[+$deleted]($deleted_style))"
added_style = "fg:green"
deleted_style = "fg:bold red"
disabled = true

[c]
symbol = " "
style = "bg:base3"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:base3"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:base2"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:overlay"
format = '[  $time ]($style)'
	
[character]
success_symbol = "[ ❯](fg:blue)"
error_symbol = "[ ✖](bold red)"

[cmd_duration]
min_time = 500
format = ' [$duration](overlay)'
# [cmd_duration]
# format = "[  $duration ]($style)"
# style = "fg:bright-white bg:18"


[palettes.mocha]
red       ="#dc322f"
maroon    ="#eba0ac"
peach     ="#fab387"
yellow    ="#fff017"
green	  ="#a6e3a1"
teal	  ="#94e2d5"
cloud     ="#89dceb"
sapphire  ="#74c7ec"
sky 	  ="#89b4fa"
blue      ="#268bd2"
cyan      ="#2aa198"
lavender  ="#b4befe"
text	  ="#cdd6f4"
subtext1  ="#bac2de"
subtext0  ="#a6adc8"
overlay2  ="#9399b2"
overlay1  ="#7f849c"
overlay   ="#6c7086"
base3	  ="#585b70"
base2	  ="#45475a"
base1	  ="#313244"
base0	  ="#1e1e2e"
smoke     ="#181825"
charcoal  ="#11111b"

